### PR TITLE
bump uwsgi to 2.0.21

### PR DESCRIPTION
**Pull request by matuskosut**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matuskosut** [comment]
@conda-forge-admin, please update circle

**Comment by matuskosut** [comment]
@conda-forge-admin, please rerender

**Comment by matuskosut** [comment]
@conda-forge-admin, please ping team

**Comment by matuskosut** [comment]
sorry for making duplicate PR, I forgot there was one and then just went on figuring out what needs to be updated to make the re-rendered build fly

**Comment by ocefpaf** [comment]
We need to remove CircleCI hook later. Also, this PR edits many autogenerated files. We need to re-render and make those changes in the recipe pins.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by matuskosut** [comment]
Hi @ocefpaf !

any tips for removing CircleCI hook? Not sure if this is about removing `.circleci` directory or is there something else to be done on your side.

I updated the pins, and then in another commit changed osx SDK version based on what I saw in python/numpy recipes.

I could use a hint with `linux_64_python3.10.____cpython` and `linux_64_python3.9.____cpython`.
When testing [earlier](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=650063&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e), I had to use older c_compiler_version to get it to build:
- python3.10: `c_compiler_version: 9`
- python3.9: `c_compiler_version: 10`

I realize that might not be the best approach, but currently with `c_compiler_version: 11` it gives strange errors:
- `libpython3.10.a' generated with GCC compiler older than 10.0` https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=650991&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=723
- `libpython3.9.a' generated with LTO version 9.4 instead of the expected 11.3` https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=650991&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=722

**Comment by matuskosut** [comment]
@conda-forge-admin, please restart ci

**Comment by matuskosut** [comment]
@ocefpaf pipelines seem happy now. Should be good to move on with this one. 

I noticed in my internal pipeline that there were some updates in python packages, so I triggered rebuild and now it clicked.

**Comment by ocefpaf** [comment]
You cannot edit the auto-generated files directly. If you need those changes we need to apply them as pins in the recipe or other config options. Any re-rendering will revert those.

**Comment by matuskosut** [comment]
@conda-forge-admin, please rerender

**Comment by matuskosut** [comment]
@ocefpaf tried to rerender again. I would really appreciate some details here.

Linux builds automagically works, I don't really want to pin anything anyway, but I am curious how come this didn't work on rerender last time (https://github.com/conda-forge/uwsgi-feedstock/runs/11018117355) ? Is there any predictable way to figure out that it's not the missing pins causing the build to fail, and what it actually is? I am seriously interested and puzzled at the same time.

Could you also help with OSX builds? I don't understand what/how to pin in the recipe here. As I tried last week this seemed to work (https://github.com/conda-forge/uwsgi-feedstock/pull/60/commits/65cfaf4637604cbff8db51bdbdb7c1bc42c26687), but if that's not allowed then I am not sure, I haven't found more in documentation.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> Could you also help with OSX builds? I don't understand what/how to pin in the recipe here.

We modify the config file conda_build_config.yaml only and the re-rendering takes care of propagating that to the auto-generated files. Thanks for your efforts here!

**Pull request merged**
