### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**
Update recipe to 2.0.14

### CODE REVIEW

**Comment by jjhelmus** [comment]
Version `2.012` fails on [OS X in Python 3.4](https://travis-ci.org/conda-forge/uwsgi-feedstock/jobs/181008239), `2.0.14` in [Python 2.7](https://travis-ci.org/conda-forge/uwsgi-feedstock/jobs/181727913).  I cannot reproduce either of these locally on my machine. @kalefranz any ideas?

**Comment by jjhelmus** [comment]
Feedstock maintainer: any idea why the OS X build failed.  I don't know enough about this package to debug the issue.

**Comment by jakirkham** [comment]
If I had to guess, it is setting too many threads for building. Maybe there is some way to override the number of threads so it only builds using 1. Even if that is not the issue, it will hopefully make it easier to debug.

**Comment by jakirkham** [comment]
I'm trying the restart the CI and see if the error was spurious strategy.

**Comment by jakirkham** [comment]
Maybe issue ( https://github.com/unbit/uwsgi/issues/1318 ) is relevant.

**Comment by jakirkham** [comment]
Last restart was somewhat productive, but we ran into an issue in testing.

```python
================== TESTING 27 =====================
>>> Spawning uWSGI python app
~/miniconda3/conda-bld/recipe_1483565166660/work ~/miniconda3/conda-bld/recipe_1483565166660/test_tmp
>>> Spawned PID 1572 , running tests
curl: (22) The requested URL returned error: 500 Internal Server Error
TESTS FAILED: uwsgi-2.0.14-py27_0
```

**Comment by jakirkham** [comment]
This still needs to be rebuilt with `conda-build` 2. However, we decided this did not constitute a blocker for moving ahead in our meeting today. It would be great if the feedstock maintainer could take a look at this and suggest fixes so they can be `conda-build` 2 compatible.

**Comment by jakirkham** [comment]
Resolved with PR ( https://github.com/conda-forge/uwsgi-feedstock/pull/4 ).

**Pull request closed without merging**
